[target.aarch64-linux-android]
ar = "<path_to_ndk_bundle>/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"
linker = "<path_to_ndk_bundle>/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "<path_to_ndk_bundle>/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar"
linker = "<path_to_ndk_bundle>/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "<path_to_ndk_bundle>/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-ar"
linker = "<path_to_ndk_bundle>/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android29-clang"

[target.x86_64-linux-android]
ar = "<path_to_ndk_bundle>/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar"
linker = "<path_to_ndk_bundle>/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android29-clang"
