[package]
name = "woff_decoder"
version = "0.2.0"
authors = ["Alex Khomich <alexkh90@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
flate2 = "1.0.6"
bytebuffer = "0.2.1"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[lib]
name = "woffdecoder"
crate-type = ["staticlib", "cdylib"]